# Generated by Django 4.0.4 on 2022-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_professor', models.CharField(max_length=20)),
                ('number_semester', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
