# Generated by Django 4.0.4 on 2022-06-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataProfessors',
            new_name='DataProfessor',
        ),
    ]
