# Generated by Django 4.0.4 on 2022-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_rename_dataprofessors_dataprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprofessor',
            name='course',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='dataprofessor',
            name='name_professor',
            field=models.CharField(max_length=26),
        ),
    ]
