# Generated by Django 4.0.4 on 2022-07-15 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_dataprofessor_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprofessor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
